name: Deploy CCGRR

on:
  push:
    branches:
      # NOTE: You may want to limit the trigger branch to be "main" or "master" etc.
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Download the useless dependiences
        run: npm install

      - name: Generate your content
        run: npm run build

      - name: Publish
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: dist
          target-branch: gh-pages